# version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    # image: nodeapp
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: nodeapi
    volumes:
     - api_node_modules:/app/node_modules
     - .:/app

    ports:
      - 3030:3030
    depends_on:
      - mongo_db

  # MongoDB Client Service
  mongo_express:
    container_name: mongo-express-client
    image: mongo-express
    # build:
    #  context: ./database
    #  dockerfile: Dockerfile
    #  target: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
    # networks:
    #   - my_network

volumes:
  mongo_data: {}
  api_node_modules:
  # frontend_node_modules: