# # version: '3.9'

# services:
#   # Mongodb service
#   mongo_db:
#     container_name: db_container
#     image: mongo:latest
#     ports:
#       - 27017:27017
#     restart: always
#     volumes:
#       - mongo_data:/data/db

#   # Node api service
#   api:
#     image: nodeapp
#     ports:
#       - 3030:3030
#     depends_on: 
#       - mongo_db

# volumes:
#   mongo_data: {}


services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: dbapp:database
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      # - ./init:/docker-entrypoint-initdb.d
  
  # MongoDB Client Service
  mongo_express:
    image: dbapp:mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db


  # Node api service
  api:
    image: dbapp:api
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}