# version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: dbapp:database
    ports:
      - 27017:27017
    # environment:
    #   # # - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_root_username
    #   # # - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_root_password
    #   # - MONGO_INITDB_ROOT_USERNAME=jeison_roblero
    #   # - MONGO_INITDB_ROOT_PASSWORD=nginx1Proxy2Server(
    #   - MONGO_INITDB_DATABASE=dealershipsDB
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d
  
  # MongoDB Client Service
  mongo_express:
    image: dbapp:mongo-express
    ports:
      - 8081:8081
    environment:
    #   - ME_CONFIG_MONGODB_ADMINUSERNAME=jeison_roblero
    #   - ME_CONFIG_MONGODB_ADMINPASSWORD=nginx1Proxy2Server(
      - ME_CONFIG_MONGODB_SERVER=mongo_db

  # Node api service
  api:
    image: dbapp:api
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db

  # Django service
  dealership:
    container_name: dealership
    image: dealership:djangowebapp
    command: gunicorn --certfile=nginx/ssl/server.crt --keyfile=nginx/ssl/private.key --bind 0.0.0.0:8000 djangoproj.wsgi:application
    ports:
      - "6000:9000"
    restart: always
    depends_on:
      - mongo_db
    environment:
      - MONGO_HOST=mongo_db
      - MONGO_PORT=27017
      - MONGO_NAME=dealershipsDB
      # - MONGO_USER=username
      # - MONGO_PASSWORD=password
      # - MONGO_AUTH_SOURCE=admin
      # - MONGO_AUTH_MECHANISM=SCRAM-SHA-1

  # Nginx service
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "7000:443"
    volumes:
      - ./nginx/nginx_conf:/etc/nginx/nginx_conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - dealership

secrets:
  mongo_root_username:
    external: true
  mongo_root_password:
    external: true

volumes:
  mongo_data: {}
