# version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: dbapp:database
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - my_network
  
  # MongoDB Client Service
  mongo_express:
    image: dbapp:mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
    networks:
      - my_network

  # Node api service
  api:
    image: dbapp:api
    ports:
      - 3030:3030
    volumes:
      - ./database/config.js:/app/config.js
    depends_on: 
      - mongo_db
    networks:
      - my_network

  # Django service
  dealership:
    container_name: dealership
    image: dealership:djangowebapp
    ports:
      - "3037:3000"
    depends_on:
      - mongo_db 
    environment:
      - MONGO_HOST=mongo_db
      - MONGO_PORT=27017
      - MONGO_NAME=dealershipsDB
    networks:
      - my_network

  # Nginx service
  nginx:
    image: nginx:latest
    ports:
      - "3031:3032"
      - "5050:443"
      - "8082:8083"
    volumes:
      - ./nginx/nginx_conf:/etc/nginx/nginx_conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - dealership
    networks:
      - my_network

secrets:
  mongo_root_username:
    external: true
  mongo_root_password:
    external: true

volumes:
  mongo_data: {}

networks:
  my_network:
    driver: bridge
